korzinkauz/urls.py
from django.contrib import admin
from django.urls import path, include
from .api import router
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("products.urls")),
    # path('api/', include('korzinkauzApi.urls')),
    path('api/', include(router.urls)),
]

products/urls.py
from django.urls import path
from .views import *

from django.conf.urls.static import static
from django.conf import settings

app_name = "ProductsApp"
urlpatterns = [
    path("", home, name="home"),
    path("product/", products, name="products"),
    path("product/create/", createProduct, name="createProduct"),
    path("product/create/<str:pk>", createProductToCategory, name="createProductToCategory"),
    path("product/update/<str:pk>/", updateProduct, name="updateProduct"),
    path("product/delete/<str:pk>/", deleteProduct, name="deleteProduct"),
    path('category/', category, name="category"),
    path("category/<str:pk>", categoryViewID, name="categoryViewID"),
    path("category/create/", createCategory, name="createCategory"),
    path("category/update/<str:pk>/", updateCategory, name="updateCategory"),
    path("category/delete/<str:pk>/", deleteCategory, name="deleteCategory"),
    path("customer/", customer, name="customer"),
    path("customer/<str:pk>", customerViewID, name="customerViewID"),
    path("customer/create/", createCustomer, name="createCustomer"),
    path("customer/update/<str:pk>/", updateCustomer, name="updateCustomer"),
    path("customer/delete/<str:pk>/", deleteCustomer, name="deleteCustomer"),
    path("order/", order, name="order"),
    path("order/create/", createOrder, name="createOrder"),
    path("order/update/<str:pk>/", updateOrder, name="updateOrder"),
    path("order/delete/<str:pk>/", deleteOrder, name="deleteOrder"),
    path("status/", status, name="status"),
    path("status/create/", createStatus, name="createStatus"),
    path("status/update/<str:pk>/", updateStatus, name="updateStatus"),
    path("status/delete/<str:pk>/", deleteStatus, name="deleteStatus"),
    path("registration/", register, name="register"),
    path("login/", user_login, name="login"),
    path("logout/",user_logout, name="logout"),
    path("user/", user_profile, name="user"),
    path("user/setting", userSetting, name="userSetting"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, null=True)
    description = models.CharField(max_length=255, null=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100, null=True)
    productCode = models.CharField(max_length=100, null=True)
    price = models.FloatField(null=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=100, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)
    phone = models.CharField(max_length=100, null=True)
    profilePic = models.ImageField(upload_to='ProfilePicture', null=True, default="defoult-user.png")
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
        
class Status(models.Model):
    name = models.CharField(max_length=100, null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class Order(models.Model):
    orderCode = models.CharField(max_length=100, null=True)
    orderDate = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    products = models.ManyToManyField(Product, null=True)
    
    def __str__(self):
        return self.orderCode

products/forms.py
from django import forms
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import *
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("first_name", "last_name", "username", "email", "password")
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))

class ProfileForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ("first_name", "last_name", "username", "email")
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))



class createProductToCategoryForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ("name", "productCode", "price", "category", "description",)

products/views.py
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import HttpResponse
from django.utils.translation import gettext as _
from django.template import RequestContext
from datetime import datetime

#
from .forms import *
from .filters import *
from .decorators import *

# Create your views here.

def home(request):
    context={
        'hello':_("Hello")
    }
    return render(request, 'products/home.html', context)
@logout_required
def register(request):    
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        customerForm = CustomerForm(data=request.POST)
        if len(request.POST['password']) == 0:
            messages.info(request, "Enter the password!")
        if len(request.POST['password']) < 8:
            messages.info(request, "Password min length 8")
        if user_form.is_valid() and customerForm.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            group = Group.objects.get(name='customer')
            user.groups.add(group)
            user.save()
            registered = True
            customer = customerForm.save(commit=False)
            customer.user = user
            customer.save()
        else:
            messages.info(request, user_form.errors)
    else:
        user_form = UserForm()
        customerForm = CustomerForm()
    return render(request, 'products/registration.html',
                    context={'user_form': user_form, "customerForm":customerForm, "registered": registered} )
    
@logout_required
def user_login(request):
    loginning = False
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['username'] = username

                loginning = True
                response = render(request, "products/login.html", {'username':username, 'loginning':loginning})
                response.set_cookie('last_connection', datetime.now())
                response.set_cookie('username', datetime.now())
                return response
        else:
            print("SOMEONE TRIED TO LOGIN and FIELD!")
            print(f"Username: {username} and password: {password}")
            messages.info(request, "Username OR Password is incurrent")
    if loginning:
        username = request.session['username']
    else:
        username = request.user
    # print(messages)
    return render(request, "products/login.html",
                    {'username':username})

@login_required
def user_logout(request):
    try:
        del request.session['username']
    except:
        pass
    logout(request)
    return redirect("/")


@login_required
def user_profile(request):
    # user = request.user
    # customer = Customer.objects.get(id=1)
    # userForm = UserForm(instance=user)
    # customerForm = CustomerForm(instance=customer)
    # orders = Order.objects.filter(customer=customer)
    # if request.method == "POST":
    #     userForm = UserForm(request.POST, instance=user)
    #     # customerForm = CustomerForm(data=request.POST, files=request.FILES, instance=customer)
    #     if userForm.is_valid():
    #         print(request.FILES)
    #         userForm.save()
    #         # customer = customerForm.save()
    #         return redirect("/user/")
    return render(request, 'products/user_profile.html',)# {'form': userForm})#, 'form2':customerForm, 'orders':orders})
@login_required
def userSetting(request):
    user = request.user
    customer = Customer.objects.get(id=1)
    userForm = ProfileForm(instance=user)
    customerForm = CustomerForm(instance=customer)
    orders = Order.objects.filter(customer=customer)
    if request.method == "POST":
        userForm = ProfileForm(request.POST, instance=user)
        customerForm = CustomerForm(data=request.POST, files=request.FILES, instance=customer)

        if customerForm.is_valid() and userForm.is_valid():
            print(request.FILES)
            userForm.save()
            customer = customerForm.save(commit=False)
            customer.user = request.user
            customer.save()
            return redirect("/user/")
        else:
            return HttpResponse("Error")
    return render(request, 'products/editProfile.html', {'form':userForm,'form2':customerForm, 'orders':orders})


@login_required
@admin_only
def categoryViewID(request, pk):
    category=Category.objects.get(id=pk)
    productS = Product.objects.filter(category=category)
    myFilter = CategoryViewProductFilter(request.GET, queryset=productS)
    productS = myFilter.qs
    my_dict = {"products": productS, "category":category, "productsLength":productS.count(),
    'myFilter':myFilter}
    return render(request, "products/view/categoryViewID.html", context=my_dict)

@login_required
@admin_only
def customerViewID(request, pk):
    customer=Customer.objects.get(id=pk)
    orderItem = Order.objects.filter(customer=customer)
    myFilter = CustomerViewOrderItem(request.GET, queryset=orderItem)
    orderItem = myFilter.qs
    my_dict = {"orderItem": orderItem, "customer":customer, "orderItemLength":orderItem.count(),
    'myFilter':myFilter}
    return render(request, "products/view/customerViewID.html", context=my_dict)





# Crud Product

@login_required
@allowed_users(['manager', 'admin'])
def products(request):
    productS = Product.objects.all()
    myFilter = ProductFilter(request.GET, queryset=productS)
    productS = myFilter.qs
    my_dict = {"products": productS,
    "myFilter":myFilter}
    return render(request, "products/products.html", context=my_dict)

@login_required
@admin_only
def createProduct(request):
    if request.method == "POST":
        productFrom = ProductForm(data=request.POST)
        print(request.POST)
        if productFrom.is_valid():
            productFrom.save(commit=True)
            return redirect("/product/")
    else:
        productFrom = ProductForm()

    return render(request, "products/create/createProduct.html", context={
            "form": productFrom,
        })

@login_required
@admin_only
def createProductToCategory(request, pk):
    MyFormSet = inlineformset_factory(Category, Product, 
        fields=("name", "productCode", 'price'), extra=5
    )
    category = Category.objects.get(id=pk)
    formset = MyFormSet(queryset=Product.objects.none(), instance=category)

    print(category)

    if request.method == "POST":
        formset = MyFormSet(request.POST, instance=category)
        print(request.POST)
        if formset.is_valid():
            formset.save()
            return redirect(f"/category/{pk}")

    return render(request, "products/create/createProductSet.html", context={
            "formset": formset,
        })

@login_required
@admin_only
def updateProduct(request, pk):
    product = Product.objects.get(id=pk)
    if request.method == "POST":
        productForm = ProductForm(data=request.POST, instance=product)
        if productForm.is_valid():
            productForm.save()
            return redirect("/product/")
    else:
        productForm = ProductForm(instance=product)

    return render(request, "products/update/updateProduct.html", context={
            "form": productForm,
        })

@login_required
@admin_only
def deleteProduct(request, pk):
    product = Product.objects.get(id=pk)
    if request.method == 'POST':
        product.delete()
        return redirect('/product/')
    return render(request, 'products/delete/deleteProduct.html', context={'item':product})

# Crud Category
@login_required
@allowed_users(['manager', 'admin'])
def category(request):
    category = Category.objects.all()
    myFilter = CategoryFilter(request.GET, queryset=category)
    category = myFilter.qs

    my_dict = {"categorys": category, "myFilter":myFilter}
    return render(request, "products/category.html",
                  context=my_dict)


@login_required
@admin_only
def createCategory(request):
    if request.method == "POST":
        categoryForm = CategoryForm(data=request.POST)
        print(request.POST)
        if categoryForm.is_valid():
            categoryForm.save()
            return redirect("/category/")
    else:
        categoryForm = CategoryForm()

    return render(request, "products/create/createCategory.html", context={
            "form": categoryForm,
        })

@login_required
@admin_only
def updateCategory(request, pk):
    category = Category.objects.get(id=pk)
    if request.method == "POST":
        categoryForm = CategoryForm(data=request.POST, instance=category)
        if categoryForm.is_valid():
            categoryForm.save()
            return redirect("/category/")
    else:
        categoryForm = CategoryForm(instance=category)

    return render(request, "products/update/updateCategory.html", context={
            "form": categoryForm,
        })

@login_required
@admin_only
def deleteCategory(request, pk):
    category = Category.objects.get(id=pk)
    if request.method == 'POST':
        category.delete()
        return redirect('/category/')
    return render(request, 'products/delete/deleteCategory.html', context={'item':category})

#Crud Customer
@login_required
@allowed_users(['manager', 'admin'])
def customer(request):
    customers = Customer.objects.all()
    myFilter = CustomerFilter(request.GET, queryset=customers)
    customers = myFilter.qs

    my_dict = {"customers": customers, "myFilter":myFilter}
    
    return render(request, "products/customer.html",

templates/products/category.html
{% extends "products/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="slide ">This is Category page</h1>

    {% if categorys %}
        <table class="slide tabel table-striped table-bordered mb-4">
        <thead class="table-dark">
            <tr>
                <th class="py-1 px-3">View</th>
                <th class="py-1 px-3">Name</th>
                <th class="py-1 px-3">Description</th>
                <th class="py-1 px-3">Edit</th>
                <th class="py-1 px-3">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for object in categorys %}
                <tr>
                    <td class="py-1 px-3">
                        <a class="btn btn-info" href="{% url 'ProductsApp:categoryViewID' object.id %}">
                            View
                        </a>
                        </td>
                    <td class="py-1 px-3">
                        {{ object.name }}
                        
                    </td>
                    <td class="py-1 px-3">
                        {{ object.description }}
                    </td>
                    <td class="py-1 px-3">
                        <a href="{% url 'ProductsApp:updateCategory' object.id %}" class="btn btn-primary a-btn-slide-text">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    </td>
                    <td class="py-1 px-3">
                        <a href="{% url 'ProductsApp:deleteCategory' object.id %}" class="btn btn-danger a-btn-slide-text">
                            <i class="bi bi-x"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
        {% else %}

    {% endif %}
    <div class="slide jumbotron my-3 mx-2">
        <h1 class="slide text-center mb-4">Create Category</h1>
        <a href="{% url 'ProductsApp:createCategory' %}" class="mb-3 w-100 btn btn-success a-btn-slide-text">
            <i class="bi bi-plus"></i>
            <span><strong>Add</strong></span>
        </a>
    </div>
    <form method="GET" class="slide">
        <h1>Filter</h1>
        {{ myFilter.form | crispy  }}
        <button class="btn btn-primary">
            Search
        </button>
    </form>
{% endblock %}

templates/products/customer.html
{% extends "products/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1 class="slide ">This is customer page</h1>

    {% if customers %}
        <table class="slide tabel table-striped table-bordered mb-4">
        <thead class="table-dark">
            <tr>
                <th class="py-1 px-3">Name</th>
                <th class="py-1 px-3">Phone</th>
                <th class="py-1 px-3">Email</th>
                <th class="py-1 px-3">Edit</th>
                <th class="py-1 px-3">Delete</th>

            </tr>
        </thead>
        <tbody>
            {% for object in customers %}
                <tr>
                    <td class="py-1 px-3">
                        {{ object.user.username }}
                    </td>
                    <td class="py-1 px-3">
                        {{ object.phone }}
                    </td>
                    <td class="py-1 px-3">
                        {{ object.user.email }}
                        
                    </td>
                    <td class="py-1 px-3">
                        <a href="{% url 'ProductsApp:updateCustomer' object.id %}" class="btn btn-primary a-btn-slide-text">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    </td>
                    <td class="py-1 px-3">
                        <a href="{% url 'ProductsApp:deleteCustomer' object.id %}" class="btn btn-danger a-btn-slide-text">
                            <i class="bi bi-x"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
        {% else %}
        <h1 class="slide alert alert-danger">Not found Customer</h1>
    {% endif %}
    <div class="slide jumbotron my-3 mx-2">
        <h1 class="text-center mb-4">Create Customer</h1>
        <a href="{% url 'ProductsApp:createCustomer' %}" class="mb-3 w-100 btn btn-success a-btn-slide-text">
            <i class="bi bi-plus"></i>
            <span><strong>Add</strong></span>
        </a>
    </div>
    <form method="GET" class="slide">
        <h1>Filter</h1>
        {{ myFilter.form | crispy  }}
        <button class="btn btn-primary">
            Search
        </button>
    </form>
{% endblock %}

templates/products/editProfile.html
{% extends "products/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    {{ form.first_name | as_crispy_field }}
    {{ form.last_name | as_crispy_field }}
    {{ form.username | as_crispy_field }}
    {{ form.email | as_crispy_field }}
    {{ form2.phone | as_crispy_field }}
    {{ form2.profilePic | as_crispy_field }}
    
    <input type="submit" value="Save profile" class="btn btn-primary">
</form>
{% endblock %}
    

templates/products/footer.html
<footer class="slide bg-light text-center text-lg-start">
  <div class="container p-4">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Footer Content</h5>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
          voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>
      <div class="col-lg-6 col-md-12 mb-8 mb-md-0">
        <h5 class="text-uppercase">Korzinka.uz</h5>

        <ul class="list-unstyled mb-0">

            <li>
              <a class="text-dark" href="{% url 'ProductsApp:home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
                <li>
                  <a class="text-dark" href="{% url 'ProductsApp:products' %}">Products</a>
                </li>
                <li>
                  <a class="text-dark" href="{% url 'ProductsApp:category' %}">Category</a>
                </li>
                <li>
                  <a class="text-dark" href="{% url 'ProductsApp:customer' %}">Customer</a>
                </li>
                <li>
                  <a class="text-dark" href="{% url 'ProductsApp:status' %}">Status</a>
                </li>
                <li>
                  <a class="text-dark" href="{% url 'ProductsApp:order' %}">Order</a>
                </li>
            {% else %}
                <li>
                  <a class="text-dark" href="{% url 'ProductsApp:register' %}">Registration</a>
                </li>
                <li>
                  <a class="text-dark" href="{% url 'ProductsApp:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-dark" href="#">Korzinka.uz</a>
  </div>
</footer>

templates/products/home.html
{% extends "products/base.html" %}
{% load i18n %}
{% block content %}
<div class="slide jumbotron mt-5">
<h1 class="slide">{% trans "This is home page" %}</h1>
<h4>{{ hello }}</h4>

</div>
{% endblock %}

templates/products/navbar.html
<nav class="slide navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'ProductsApp:home' %}">Korzinka.uz</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav col-sm-10">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'ProductsApp:home' %}">Home</a>
        </li>
        
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ProductsApp:products' %}">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ProductsApp:category' %}">Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ProductsApp:customer' %}">Customer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ProductsApp:status' %}">Status</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ProductsApp:order' %}">Order</a>
                </li>
                {% endif %}
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ProductsApp:register' %}">Registration</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'ProductsApp:login' %}" class="nav-link">Log in</a>
            </li>
        {% endif %}

    </ul>
    <ul class="navbar-nav col-sm-2">
        <li class="nav-item f-right">            
            <a href="#" class="nav-link">{{ user }}</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'ProductsApp:logout' %}" class="nav-link">Log out</a>
        </li>
        {% endif %}
        
    </ul>
  </div>
</nav>

templates/products/order.html
{% extends "products/base.html" %}
{% block content %}
    <h1 class="slide ">This is order page</h1>
    {% if orders %}
        <table class="slide tabel table-striped table-bordered mb-4">
        <thead class="table-dark">
            <tr>
                <th class="py-1 px-3">orderCode</th>
                <th class="py-1 px-3">status</th>
                <th class="py-1 px-3">Edit</th>
                <th class="py-1 px-3">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for object in orders %}
                <tr>
                    <td class="py-1 px-3">
                        {{ object.orderCode }}
                    </td>
                    <td class="py-1 px-3">
                        {{ object.status }}
                    </td>
                    <td class="py-1 px-3">
                        <a href="{% url 'ProductsApp:updateOrder' object.id %}" class="btn btn-primary a-btn-slide-text">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    </td>
                    <td class="py-1 px-3">
                        <a href="{% url 'ProductsApp:deleteOrder' object.id %}" class="btn btn-danger a-btn-slide-text">
                            <i class="bi bi-x"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
        {% else %}
        <h1 class="slide alert alert-danger">Not found Orders</h1>
    {% endif %}
    <div class="slide jumbotron my-3 mx-2">
        <h1 class="slide text-center mb-4">Create Order</h1>
        <a  href="{% url 'ProductsApp:createOrder' %}" class="slide mb-3 w-100 btn btn-success a-btn-slide-text">
            <i class="bi bi-plus"></i>
            <span><strong>Add</strong></span>
        </a>
    </div>
{% endblock %}

templates/products/products.html
{% extends "products/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <h1 class="slide ">This is products page</h1>
    
    


    {% if products %}
        <table class="slide tabel table-striped table-bordered mb-4">
            <thead class="table-dark">
                <tr>
                    <th class="py-1 px-3">Name</th>
                    <th class="py-1 px-3">productCode</th>
                    <th class="py-1 px-3">Price</th>
                    <th class="py-1 px-3">category</th>
                    <th class="py-1 px-3">description</th>
                    <th class="py-1 px-3">date_created</th>
                    <th class="py-1 px-3">Edit</th>
                    <th class="py-1 px-3">Delete</th>

                </tr>
            </thead>
            <tbody>
                {% for object in products %}
                    <tr>
                        <td class="py-1 px-3">
                            {{ object.name }}
                        </td>
                        <td class="py-1 px-3">
                            {{ object.productCode }}
                        </td>
                        <td class="py-1 px-3">
                            {{ object.price }}
                        </td>
                        <td class="py-1 px-3">
                            {{ object.category }}
                        </td>
                        <td class="py-1 px-3">
                            {{ object.description }}
                        </td>
                        <td class="py-1 px-3">
                            {{ object.date_created }}
                        </td>
                        <td class="py-1 px-3">
                            <a href="{% url 'ProductsApp:updateProduct' object.id %}" class="btn btn-primary a-btn-slide-text">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                        </td>
                        <td class="py-1 px-3">
                            <a href="{% url 'ProductsApp:deleteProduct' object.id %}" class="btn btn-danger a-btn-slide-text">
                                <i class="bi bi-x"></i>
                            </a>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h1 class="slide alert alert-danger">Not found Products</h1>
    {% endif %}
    <div class="slide jumbotron my-3 mx-2">
        <h1 class="text-center mb-4">Create Products</h1>
        <a href="{% url 'ProductsApp:createProduct' %}" class="mb-3 w-100 btn btn-success a-btn-slide-text">
            <i class="bi bi-plus"></i>
            <span><strong>Add</strong></span>
        </a>
    </div>
    <form method="GET" class="slide">
        <h1>Filter</h1>
        {{ myFilter.form | crispy  }}
        <button class="btn btn-primary">
            Search
        </button>
    </form>    
{% endblock %}